name: Deploy to Cloud Run

#on:
#  push:
#    branches:
#      - main
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: devopschallenge-456122        # Defina o ID do projeto
      REGION: southamerica-east1               # Defina a região
      IMAGE_NAME_PYTHON: python-app                   # Defina o nome da imagem
      IMAGE_NAME_NODEAPP: node-app                   # Defina o nome da imagem

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with: 
          credentials_json: "${{ secrets.GCP_SA_KEY }}"  # Referência ao segredo do JSON da chave do serviço

      - name: Build and push Python app
        run: |
          gcloud builds submit ./app-python --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME_PYTHON }}
      
      - name: Build and push NODE app
        run: |
          gcloud builds submit ./app-node --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME_NODEAPP }}

      # Terraform setup
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: "1.2.3"

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Caminho para o diretório do Terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var="project_id=${{ env.PROJECT_ID }}" -var="region=${{ env.REGION }}" -var="python_image=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME_PYTHON }}" -var="node_image=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME_NODEAPP }}" -var="python_service_name=pythonapp" -var="node_service_name=nodeapp"
        working-directory: ./terraform
        
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform

      - name: Output Cloud Run URL for Python App
        run: echo "Python App Cloud Run URL= $(terraform output -raw python_service_url)"

      - name: Output Cloud Run URL for Node.js App
        run: echo "Node.js App Cloud Run URL= $(terraform output -raw node_service_url)"
